### ISSUE TITLE
Error with Bolzano open data

### ISSUE THREAD

**Issue by airon90** [OneBusAway/onebusaway-vdv-modules#6]
Hi,
I tried using your VDV to GTFS converter in order to convert [Bolzano open data](http://sasabus.org/opendata) to GTFS file. I downloaded [their file](http://open.sasabz.it/files/vdv.zip) and your tool as explained in [README.md](README.md) but this is the backtrace:

```
2016-09-05 10:39:55,040 INFO  [Vdv452Reader.java:106] : reading entities: org.onebusaway.vdv452.model.BaseVersion
org.onebusaway.csv_entities.exceptions.MissingRequiredEntityException: missing required entity: type=org.onebusaway.vdv452.model.BaseVersion filename=MENGE_BASIS_VERSIONEN.x10
    at org.onebusaway.csv_entities.CsvEntityReader.openInputStreamForEntityClass(CsvEntityReader.java:197)
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:113)
    at org.onebusaway.vdv452.Vdv452Reader.run(Vdv452Reader.java:107)
    at org.onebusaway.vdv452.Vdv452Reader.run(Vdv452Reader.java:100)
    at org.onebusaway.vdv452.Vdv452ToGtfsConverter.run(Vdv452ToGtfsConverter.java:54)
    at org.onebusaway.vdv452.Vdv452ToGtfsConverterMain.runApplication(Vdv452ToGtfsConverterMain.java:95)
    at org.onebusaway.vdv452.Vdv452ToGtfsConverterMain.run(Vdv452ToGtfsConverterMain.java:54)
    at org.onebusaway.vdv452.Vdv452ToGtfsConverterMain.main(Vdv452ToGtfsConverterMain.java:42)
```

**Comment by barbeau** [comment]
@Airon90 From some quick testing, it looks like the files inside the zip archive should be named `*.x10`, not `*.X10`.  I don't know enough about VDV-452 to saw whether this is part of that standard (and I didn't write this tool), but if you change all the file extensions in the zip to `.x10` I think it should work.  I'll close this for now, but feel free to re-open if that doesn't fix it.

**Comment by tafflin** [comment]
@barbeau I actuall have the same issue when trying to convert Transport for Ireland data. The file extentions are all *.x10 in lowercase

**Comment by chadselph** [comment]
I got this same error with a German VDV file where the file names were all *.x10.

There seemed to be a problem with the fact that the files were inside a subdirectory in the zip.
